name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install deps
        run: bun install
      - name: Publish package to JSR
        run: bun run publish:jsr
      - name: Publish package to npm
        run: npm publish
